#Subject.create(name: "小学语文")
#Subject.create(name: "小学数学")
#Subject.create(name: "小学英语")
#Subject.create(name: "初中语文")
#Subject.create(name: "初中数学")
#Subject.create(name: "初中英语")
#Subject.create(name: "初中物理")
#Subject.create(name: "初中化学")
#Subject.create(name: "初中生物")
#Subject.create(name: "初中地理")
#Subject.create(name: "初中政治")
#Subject.create(name: "初中历史")
#Subject.create(name: "高中历史")
#Subject.create(name: "高中语文")
#Subject.create(name: "高中数学")
#Subject.create(name: "高中英语")
#Subject.create(name: "高中地理")
#Subject.create(name: "高中政治")
#Subject.create(name: "高中物理")
#Subject.create(name: "高中生物")
#Subject.create(name: "高中化学")

#User.create!(name: "Bob1", email: "bob1@gmail.com", password: "123456", password_confirmation: "123456", role: "tutor")
#User.create!(name: "Bob2", email: "bob2@gmail.com", password: "123456", password_confirmation: "123456", role: "tutor")
#User.create!(name: "Bob3", email: "bob3@gmail.com", password: "123456", password_confirmation: "123456", role: "tutor")
#User.create!(name: "Bob4", email: "bob4@gmail.com", password: "123456", password_confirmation: "123456", role: "tutor")
#User.create!(name: "Bob5", email: "bob5@gmail.com", password: "123456", password_confirmation: "123456", role: "tutor")
#User.create!(name: "Bob6", email: "bob6@gmail.com", password: "123456", password_confirmation: "123456", role: "tutor")
#User.create!(name: "Bob7", email: "bob7@gmail.com", password: "123456", password_confirmation: "123456", role: "tutor")
#User.create!(name: "Bob8", email: "bob8@gmail.com", password: "123456", password_confirmation: "123456", role: "tutor")
#TutorInfo.create!(user_id: 12, gender: "男", username: "蔡教员", subject_list: "小学英语", date_of_birth: "1953-05-01", major: "师范专业", school: "华南师大", identity: "在校学生", area: "海珠", address: "组影", phone: "13421749821", qq: 1156974285, fee: "10元/小时", time: "面谈", experience: "一对一辅导一名世外小学的学生，由班级后十名，先已稳达平均分，并在上个学期的期末考试中，考到班级前十名，获得奖学金。  2.带有三个初中英语小班，学生成绩显著提高：两个基础班里的学生由平均分以下十几分，提升至每次考试都能达到平均分。一个培优班里的学生由原来班级前十，现已每次考试稳定在班级前三。  3.高三英语小班中共有五名学生，原本每次考试都在90分以下（满分150），现四名学生成绩都已达到100分左右，考入上海市二本高校。", status: true)
#TutorInfo.create!(user_id: 13, gender: "女", username: "黄教员", subject_list: "高中数学", date_of_birth: "1953-05-01", major: "电器专业", school: "广州大学", identity: "在校学生", area: "海珠", address: "组影", phone: "13421749821", qq: 1156974285, fee: "10元/小时", time: "面谈", experience: "一对一辅导一名世外小学的学生，由班级后十名，先已稳达平均分，并在上个学期的期末考试中，考到班级前十名，获得奖学金。  2.带有三个初中英语小班，学生成绩显著提高：两个基础班里的学生由平均分以下十几分，提升至每次考试都能达到平均分。一个培优班里的学生由原来班级前十，现已每次考试稳定在班级前三。  3.高三英语小班中共有五名学生，原本每次考试都在90分以下（满分150），现四名学生成绩都已达到100分左右，考入上海市二本高校。", status: true)
#TutorInfo.create!(user_id: 14, gender: "男", username: "宋教员", subject_list: "初中物理", date_of_birth: "1953-05-01", major: "城市规划专业", school: "广东工业大学", identity: "在校学生", area: "海珠", address: "组影", phone: "13421749821", qq: 1156974285, fee: "10元/小时", time: "面谈", experience: "一对一辅导一名世外小学的学生，由班级后十名，先已稳达平均分，并在上个学期的期末考试中，考到班级前十名，获得奖学金。  2.带有三个初中英语小班，学生成绩显著提高：两个基础班里的学生由平均分以下十几分，提升至每次考试都能达到平均分。一个培优班里的学生由原来班级前十，现已每次考试稳定在班级前三。  3.高三英语小班中共有五名学生，原本每次考试都在90分以下（满分150），现四名学生成绩都已达到100分左右，考入上海市二本高校。", status: true)
#TutorInfo.create!(user_id: 15, gender: "女", username: "李教员", subject_list: "小学英语", date_of_birth: "1953-05-01", major: "人文专业", school: "华南理工", identity: "在校学生", area: "海珠", address: "组影", phone: "13421749821", qq: 1156974285, fee: "10元/小时", time: "面谈", experience: "一对一辅导一名世外小学的学生，由班级后十名，先已稳达平均分，并在上个学期的期末考试中，考到班级前十名，获得奖学金。  2.带有三个初中英语小班，学生成绩显著提高：两个基础班里的学生由平均分以下十几分，提升至每次考试都能达到平均分。一个培优班里的学生由原来班级前十，现已每次考试稳定在班级前三。  3.高三英语小班中共有五名学生，原本每次考试都在90分以下（满分150），现四名学生成绩都已达到100分左右，考入上海市二本高校。", status: true)
#TutorInfo.create!(user_id: 16, gender: "男", username: "陈教员", subject_list: "小学数学", date_of_birth: "1953-05-01", major: "师范专业", school: "北京师大", identity: "在校学生", area: "海珠", address: "组影", phone: "13421749821", qq: 1156974285, fee: "10元/小时", time: "面谈", experience: "一对一辅导一名世外小学的学生，由班级后十名，先已稳达平均分，并在上个学期的期末考试中，考到班级前十名，获得奖学金。  2.带有三个初中英语小班，学生成绩显著提高：两个基础班里的学生由平均分以下十几分，提升至每次考试都能达到平均分。一个培优班里的学生由原来班级前十，现已每次考试稳定在班级前三。  3.高三英语小班中共有五名学生，原本每次考试都在90分以下（满分150），现四名学生成绩都已达到100分左右，考入上海市二本高校。", status: true)
#TutorInfo.create!(user_id: 17, gender: "女", username: "花教员", subject_list: "高中语文", date_of_birth: "1953-05-01", major: "英语专业", school: "济南大学", identity: "在校学生", area: "海珠", address: "组影", phone: "13421749821", qq: 1156974285, fee: "10元/小时", time: "面谈", experience: "一对一辅导一名世外小学的学生，由班级后十名，先已稳达平均分，并在上个学期的期末考试中，考到班级前十名，获得奖学金。  2.带有三个初中英语小班，学生成绩显著提高：两个基础班里的学生由平均分以下十几分，提升至每次考试都能达到平均分。一个培优班里的学生由原来班级前十，现已每次考试稳定在班级前三。  3.高三英语小班中共有五名学生，原本每次考试都在90分以下（满分150），现四名学生成绩都已达到100分左右，考入上海市二本高校。", status: true)
#TutorInfo.create!(user_id: 18, gender: "男", username: "李教员", subject_list: "高中英语", date_of_birth: "1953-05-01", major: "数学专业", school: "华南师大", identity: "在校学生", area: "海珠", address: "组影", phone: "13421749821", qq: 1156974285, fee: "10元/小时", time: "面谈", experience: "一对一辅导一名世外小学的学生，由班级后十名，先已稳达平均分，并在上个学期的期末考试中，考到班级前十名，获得奖学金。  2.带有三个初中英语小班，学生成绩显著提高：两个基础班里的学生由平均分以下十几分，提升至每次考试都能达到平均分。一个培优班里的学生由原来班级前十，现已每次考试稳定在班级前三。  3.高三英语小班中共有五名学生，原本每次考试都在90分以下（满分150），现四名学生成绩都已达到100分左右，考入上海市二本高校。", status: true)
#TutorInfo.create!(user_id: 19, gender: "女", username: "花教员", subject_list: "初中化学", date_of_birth: "1953-05-01", major: "政治专业", school: "华南师大", identity: "在校学生", area: "海珠", address: "组影", phone: "13421749821", qq: 1156974285, fee: "10元/小时", time: "面谈", experience: "一对一辅导一名世外小学的学生，由班级后十名，先已稳达平均分，并在上个学期的期末考试中，考到班级前十名，获得奖学金。  2.带有三个初中英语小班，学生成绩显著提高：两个基础班里的学生由平均分以下十几分，提升至每次考试都能达到平均分。一个培优班里的学生由原来班级前十，现已每次考试稳定在班级前三。  3.高三英语小班中共有五名学生，原本每次考试都在90分以下（满分150），现四名学生成绩都已达到100分左右，考入上海市二本高校。", status: true)
9.times do |n|
  User.create!(name: "Mary#{n}", email: "Mary#{n}@gmail.com", password: "123456", password_confirmation: "123456", role: "student")
end
StudentInfo.create!(user_id: 20, gender: "男", username: "蔡先生", grade: "初一", subject_list: "初中英语", area: "海珠", address: "组影", phone: "13421749821", fee: "10元/小时", time: "面谈" , demand: "英语口语好的，经验丰富的教员，家长看简历！", status: true)
StudentInfo.create!(user_id: 21, gender: "女", username: "黄小姐", grade: "高一", subject_list: "高中英语", area: "海珠", address: "组影", phone: "13421749821", fee: "10元/小时", time: "面谈" , demand: "家长看简历！", status: true)
StudentInfo.create!(user_id: 22, gender: "男", username: "蔡先生", grade: "初一", subject_list: "初中英语", area: "海珠", address: "组影", phone: "13421749821", fee: "10元/小时", time: "面谈" , demand: "经验丰富的教员", status: true)
StudentInfo.create!(user_id: 23, gender: "男", username: "李小姐", grade: "六年级", subject_list: "小学数学", area: "海珠", address: "组影", phone: "13421749821", fee: "10元/小时", time: "面谈" , demand: "江浙沪的大学生，亲切的！家长看简历", status: true)
StudentInfo.create!(user_id: 24, gender: "女", username: "白小姐", grade: "五年级", subject_list: "小学语文", area: "海珠", address: "组影", phone: "13421749821", fee: "10元/小时", time: "面谈" , demand: "在职初中数学老师。学员需要看简历后，请您先申请勿致电天天家教网，若被选中本站将主动通知！", status: true)
StudentInfo.create!(user_id: 25, gender: "女", username: "蔡先生", grade: "一年级", subject_list: "小学数学", area: "海珠", address: "组影", phone: "13421749821", fee: "10元/小时", time: "面谈" , demand: "优秀的大学生，有经验的，长久教的，家长要看简历", status: true)
StudentInfo.create!(user_id: 26, gender: "男", username: "欧先生", grade: "高三", subject_list: "高中物理", area: "海珠", address: "组影", phone: "13421749821", fee: "10元/小时", time: "面谈" , demand: "优秀的大学生，有经验的，家长看简历，教员中介费减少", status: true)
StudentInfo.create!(user_id: 27, gender: "男", username: "廖先生", grade: "高二", subject_list: "高中地理", area: "海珠", address: "组影", phone: "13421749821", fee: "10元/小时", time: "面谈" , demand: "地理优秀的大学生，有经验的，家长看简历，教员中介费减少", status: true)
StudentInfo.create!(user_id: 28, gender: "女", username: "林先生", grade: "初二", subject_list: "初中化学", area: "海珠", address: "组影", phone: "13421749821", fee: "10元/小时", time: "面谈" , demand: "化学优秀的大学生，有经验的，家长看简历，教员中介费减少", status: true)
